from .animais import Animais
from .parede import Parede
from .mago import Mago
from .rio import Rio
from .projectile import Projectile
from .dragao import Dragao
from .menu import Menu
from .coletaveis import Coletaveis
from .pausemenu import PauseMenu